<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <PackageId>CryptoConnectionString</PackageId>
	  <Version>1.0.1</Version>
	  <Authors>Juliano Nascimento</Authors>
	  <Description>
		  Criptografia e descriptografia seguras para strings de conexão com o provedor de integração
		  e configuração appsettings.json
	  </Description>
	  <PackageTags>connectionstrings, encryption, security, database, appsettings, configuration</PackageTags>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
		<!-- I.e. all modern/supported non-Framework .NET SKUs -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
